# Develop override settings

url: http://localhost:4000

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded

github: [metadata] encoding: UTF-8 kramdown: input: GFM hard_wrap: false